from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from functools import wraps
from typing import TYPE_CHECKING, TypeVar

import numpy as np

from graphi_RU import generate_graph
from harmony import harmony

if TYPE_CHECKING:
    from collections.abc import Callable

    import networkx as nx

R = TypeVar('R')


class ConnectionistSolver:
    """Connectionist (neural network) solver for emotional coherence model.

    Performs iterative updates of activations (a) and valences (v).
    """

    @dataclass
    class History:
        """Used for keeping track of activations, valences and harmony over time for debugging and analysis."""

        a: list[list[np.float64]]
        v: list[list[np.float64]]
        H: list[np.float64]

    _lr: float
    _decay: float
    _normalisation_function: Callable[[np.ndarray], np.float64]
    _tolerance: float
    _max_steps: int
    _history: History
    _solved: bool
    _has_converged: bool
    _steps_taken: int

    _graph: nx.Graph
    _new_graph: nx.Graph  # Build the _new_graph based on the _graph and then swap.

    def __init__(
        self,
        graph: nx.Graph,
        lr: float = 1.0,
        decay: float = 0.05,
        normalisation_function: Callable[[np.ndarray], np.float64] | None = None,
        tolerance: float = 1e-6,
        max_steps: int = 1000,
    ) -> None:
        """Initialize the ConnectionistSolver.

        Args:
            graph (networkx.Graph): Graph following the same structure as the ones generated by `graphs.generate_graph`.
            lr (float): Learning rate.
            decay (float): Strength of the decay that is applied to the previous valence/activation when updating their
                value.
            normalisation_function (Callable[[np.ndarray], np.float64]): Normalisation function. Maps multiple values
                (impact of the nodes connected to a node) to a single value in range [-1, 1]. If `None`, takes the mean
                of the given values.
            tolerance (float): Convergence threshold. Stop when changes are smaller than this value.
            max_steps (int): Maximum number of update iterations.
        """
        if max_steps < 1:
            raise ValueError(f"`max_steps` must be at least 1 but was {max_steps}.")

        self._graph = graph.copy()
        self._new_graph = graph.copy()
        self._lr = lr
        self._decay = decay

        if normalisation_function is None:
            self._normalisation_function = lambda a: a.mean()
        else:
            self._normalisation_function = normalisation_function

        self._tolerance = tolerance
        self._max_steps = max_steps
        self._history = self.History([], [], [])
        self._solved = False
        self._has_converged = False
        self._steps_taken = 0

    def _update_node(self, node_id: int) -> None:
        """Update the activation (a) and valence (v) of a single node.

        Values are taken from _graph and saved to _new_graph.

        Formulas:
        a_j(t+1) = a_j(t) + ( f(∑_i w_aij * a_i(t)) + w_vj * v_j(t) ) / 2
        v_j(t+1) = v_j(t) + ( f(∑_i w_vij * v_i(t)) + w_aj * a_j(t) ) / 2

        Important naming convention:
        - graph.nodes[node_id]['w_a'] = w_vj (valence --> activation influence)
        - graph.nodes[node_id]['w_v'] = w_aj (activation --> valence influence)

        Args:
            node_id (int): ID of the node to update.

        Returns:
            tuple[float, float]: New (activation, valence) values for the node.
        """
        node_data: dict[str, np.float64] = self._graph.nodes[node_id]

        # Collect influences from neighboring nodes.
        num_neighbours = len(self._graph.edges(node_id, data=True))
        a: np.ndarray = np.empty(num_neighbours + 1, dtype=np.float64)
        v: np.ndarray = np.empty(num_neighbours + 1, dtype=np.float64)
        for i, (_, neighbor, edge_attr) in enumerate(self._graph.edges(node_id, data=True)):
            a[i] = edge_attr['w_a'] * self._graph.nodes[neighbor]['a']
            v[i] = edge_attr['w_v'] * self._graph.nodes[neighbor]['v']

        # Add influence from the node's own valence and activation.
        a[-1] = node_data['w_v'] * node_data['v']
        v[-1] = node_data['w_a'] * node_data['a']

        # Add influence of VALENCE.
        if node_data['w_inherent_valence'] != 0:
            v = np.append(v, node_data['w_inherent_valence'])

        # Apply normalisation function.
        sum_a = self._normalisation_function(a)
        sum_v = self._normalisation_function(v)

        # Compute new activation/valence value.
        a_new = node_data['a'] * (1 - self._decay) + self._lr * sum_a
        v_new = node_data['v'] * (1 - self._decay) + self._lr * sum_v

        # Clip to valid range [-1, 1].
        a_new = a_new.clip(-1, 1)
        v_new = v_new.clip(-1, 1)

        # Assign new activation/valence to graph.
        self._new_graph.nodes[node_id]['a'] = a_new
        self._new_graph.nodes[node_id]['v'] = v_new

    def solve(self) -> None:
        """Run the iterative connectionist algorithm until convergence.

        Updates all nodes simultaneously each iteration.
        Stops when changes are small enough or max_steps is reached.
        """
        # Add initial values to history.
        self._history.H.append(harmony(self._graph))
        self._history.a.append([data['a'] for _, data in self._graph.nodes(data=True)])
        self._history.v.append([data['v'] for _, data in self._graph.nodes(data=True)])

        for step in range(self._max_steps):
            # Update all nodes.
            for node_id in self._graph.nodes:
                self._update_node(node_id)

            # Check convergence by maximum change.
            diff_a: np.ndarray = np.abs(
                [
                    data_new['a'] - data_curr['a']
                    for (_, data_new), (_, data_curr) in zip(
                        self._new_graph.nodes(data=True), self._graph.nodes(data=True), strict=True
                    )
                ]
            )
            diff_v = np.abs(
                [
                    data_new['v'] - data_curr['v']
                    for (_, data_new), (_, data_curr) in zip(
                        self._new_graph.nodes(data=True), self._graph.nodes(data=True), strict=True
                    )
                ]
            )

            max_diff: np.float64 = max(np.max(diff_a), np.max(diff_v))

            # Update history.
            self._history.H.append(harmony(self._new_graph))
            self._history.a.append([data['a'] for _, data in self._new_graph.nodes(data=True)])
            self._history.v.append([data['v'] for _, data in self._new_graph.nodes(data=True)])

            # Swap graphs.
            self._graph, self._new_graph = self._new_graph, self._graph

            # Stop if converged.
            if max_diff < self._tolerance:
                self._steps_taken = step + 1  # Add 1 because indexing starts at 0.
                self._solved = True
                self._has_converged = True
                return

        self._steps_taken = step + 1  # type: ignore[reportPossiblyUnboundVariable]
        self._solved = True

    @staticmethod
    def _reset(func: Callable[..., R]) -> Callable[..., R]:
        @wraps(func)
        def wrapper(self: ConnectionistSolver, *args, **kwargs) -> R:
            self._solved = False
            self._has_converged = False
            self._steps_taken = 0
            self._history = self.History([], [], [])
            return func(self, *args, **kwargs)

        return wrapper

    @staticmethod
    def _requires_solved(func: Callable[..., R]) -> Callable[..., R]:
        @wraps(func)
        def wrapper(self: ConnectionistSolver, *args, **kwargs) -> R:
            if not self._solved:
                raise RuntimeError(
                    f"Cannot access `{func.__name__}` before calling `solve`. If you change any properties, `solve` "
                    "must be called again."
                )
            return func(self, *args, **kwargs)

        return wrapper

    @property
    def lr(self) -> float:
        """Learning rate."""
        return self._lr

    @lr.setter
    @_reset
    def lr(self, value: float) -> None:
        self._lr = value

    @property
    def decay(self) -> float:
        """Decay."""
        return self._decay

    @decay.setter
    @_reset
    def decay(self, value: float) -> None:
        self._decay = value

    @property
    def normalisation_function(self) -> Callable[[np.ndarray], np.float64]:
        """Reference to normalisation function.

        Maps multiple values (impact of the nodes connected to a node) to a single value in range [-1, 1]. If `None`,
        takes the mean of the given values.
        """
        return self._normalisation_function

    @normalisation_function.setter
    @_reset
    def normalisation_function(self, value: Callable[[np.ndarray], np.float64]) -> None:
        self._normalisation_function = value

    @property
    def tolerance(self) -> float:
        """Convergence threshold. Stop when changes are smaller than this value."""
        return self._tolerance

    @tolerance.setter
    @_reset
    def tolerance(self, value: float) -> None:
        self._tolerance = value

    @property
    def max_steps(self) -> int:
        """Maximum number of update iterations."""
        return self._max_steps

    @max_steps.setter
    @_reset
    def max_steps(self, value: int) -> None:
        self._max_steps = value

    @property
    @_requires_solved
    def history(self) -> History:
        """History keeping track of activations, valences and harmony over time for debugging and analysis."""
        return deepcopy(self._history)

    @property
    @_requires_solved
    def harmony(self) -> np.float64:
        """Harmony of the final assignment that the network converged to."""
        return self._history.H[-1]

    @property
    def solved(self) -> bool:
        """Whether the graph has been solved."""
        return self._solved

    @property
    @_requires_solved
    def has_converged(self) -> bool:
        """True if the algorithm has converged rather than stopped because of reaching the maximum steps."""
        return self._has_converged

    @property
    @_requires_solved
    def steps_taken(self) -> int:
        """The number of steps taken for finding the solution."""
        return self._steps_taken

    @property
    def graph(self) -> nx.Graph:
        """A copy of the solved graph or unsolved graph if `solve` hasn't been called yet."""
        return self._graph.copy()

    @graph.setter
    @_reset
    def graph(self, graph: nx.Graph) -> None:
        self._graph = graph.copy()
        self._new_graph = graph.copy()


# Example
if __name__ == "__main__":
    # 1. Создаём граф
    graph = generate_graph(4, 5, 1, seed=42)

    # 2. Создаём решатель
    solver = ConnectionistSolver(
        graph=graph,
        #lr=0.5,           # Медленнее учимся
        #decay=0.1,        # Сильнее забываем старое
        tolerance=1e-4,   # Более грубая сходимость
        max_steps=500     # Не больше 500 итераций
    )

    # 3. Запускаем!
    final_harmony = solver.solve()

    # 4. Получаем результаты
    if solver.has_converged:
        print(f"Сошлось за {solver.steps_taken} шагов")
        print(f"Финальная гармония: {solver.harmony}")
        
        # Можно посмотреть историю
        history = solver.history
        for step in range(len(history.H)):
            print(f"Шаг {step}: H = {history.H[step]:.4f}")
